project:
  type: website

website:
  title: "QuART Lab"
  navbar:
    left:
      - href: intro.ipynb
        text: Home
      - miembros.ipynb

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: false

