project:
  type: website
  #pre-render: update_publications.py

website:
  title: "QuART Lab"
  navbar:
    left:
      - href: intro.ipynb
        text: Home
      - href: miembros.ipynb
        text: Miembros
      - href: software.ipynb
        text: Software
      - href: publicaciones.ipynb
        text: Publicaciones 
      - href: contacto.qmd
        text: Contacto

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: false

